import modal
import os
import json
import re

app = modal.App("medgemma-dual-agent-v11")

image = (
    modal.Image.debian_slim(python_version="3.11")
    .pip_install(
        "torch",
        "transformers>=4.40.0",
        "accelerate",
        "bitsandbytes",
        "pillow",
        "fastapi",
        "pydantic",
        "TotalSegmentator",
        "nibabel",
        "scipy",
        "pydicom",
        "requests",
        "dicom2nifti",
        "httpx",
        "PyJWT",
        "supabase",
    )
    .env({
    "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True",
})
    .add_local_dir(".", remote_path="/root")
)

model_cache = modal.Volume.from_name("medgemma-cache", create_if_missing=True)

CT_STRUCTURES = [
    "spleen",
    "kidney_right",
    "kidney_left",
    "gallbladder",
    "liver",
    "stomach",
    "pancreas",
    "adrenal_gland_right",
    "adrenal_gland_left",
    "lung_upper_lobe_left",
    "lung_lower_lobe_left",
    "lung_upper_lobe_right",
    "lung_middle_lobe_right",
    "lung_lower_lobe_right",
    "esophagus",
    "trachea",
    "thyroid_gland",
    "small_bowel",
    "duodenum",
    "colon",
    "urinary_bladder",
    "prostate",
    "kidney_cyst_left",
    "kidney_cyst_right",
    "sacrum",
    "vertebrae_L5",
    "vertebrae_L4",
    "vertebrae_L3",
    "vertebrae_L2",
    "vertebrae_L1",
    "vertebrae_T12",
    "vertebrae_T11",
    "vertebrae_T10",
    "vertebrae_T9",
    "vertebrae_T8",
    "vertebrae_T7",
    "vertebrae_T6",
    "vertebrae_T5",
    "vertebrae_T4",
    "vertebrae_T3",
    "vertebrae_T2",
    "vertebrae_T1",
    "vertebrae_C7",
    "vertebrae_C6",
    "vertebrae_C5",
    "vertebrae_C4",
    "vertebrae_C3",
    "vertebrae_C2",
    "vertebrae_C1",
    "heart",
    "aorta",
    "pulmonary_vein",
    "brachiocephalic_trunk",
    "subclavian_artery_right",
    "subclavian_artery_left",
    "common_carotid_artery_right",
    "common_carotid_artery_left",
    "brachiocephalic_vein_left",
    "brachiocephalic_vein_right",
    "atrial_appendage_left",
    "superior_vena_cava",
    "inferior_vena_cava",
    "portal_vein_and_splenic_vein",
    "iliac_artery_left",
    "iliac_artery_right",
    "iliac_vena_left",
    "iliac_vena_right",
    "humerus_left",
    "humerus_right",
    "scapula_left",
    "scapula_right",
    "clavicula_left",
    "clavicula_right",
    "femur_left",
    "femur_right",
    "hip_left",
    "hip_right",
    "spinal_cord",
    "gluteus_maximus_left",
    "gluteus_maximus_right",
    "gluteus_medius_left",
    "gluteus_medius_right",
    "gluteus_minimus_left",
    "gluteus_minimus_right",
    "autochthon_left",
    "autochthon_right",
    "iliopsoas_left",
    "iliopsoas_right",
    "brain",
    "skull",
    "rib_left_1",
    "rib_left_2",
    "rib_left_3",
    "rib_left_4",
    "rib_left_5",
    "rib_left_6",
    "rib_left_7",
    "rib_left_8",
    "rib_left_9",
    "rib_left_10",
    "rib_left_11",
    "rib_left_12",
    "rib_right_1",
    "rib_right_2",
    "rib_right_3",
    "rib_right_4",
    "rib_right_5",
    "rib_right_6",
    "rib_right_7",
    "rib_right_8",
    "rib_right_9",
    "rib_right_10",
    "rib_right_11",
    "rib_right_12",
    "sternum",
    "costal_cartilages",
    "lung_vessels",
    "lung_trachea_bronchia",
    "body",
    "body_trunc",
    "body_extremities",
    "skin",
    "intracerebral_hemorrhage",
    "hip_implant",
    "pleural_effusion",
    "pericardial_effusion",
    "eye_left",
    "eye_right",
    "eye_lens_left",
    "eye_lens_right",
    "optic_nerve_left",
    "optic_nerve_right",
    "parotid_gland_left",
    "parotid_gland_right",
    "submandibular_gland_right",
    "submandibular_gland_left",
    "nasopharynx",
    "oropharynx",
    "hypopharynx",
    "nasal_cavity_right",
    "nasal_cavity_left",
    "auditory_canal_right",
    "auditory_canal_left",
    "soft_palate",
    "hard_palate",
    "masseter_right",
    "masseter_left",
    "temporalis_right",
    "temporalis_left",
    "lateral_pterygoid_right",
    "lateral_pterygoid_left",
    "medial_pterygoid_right",
    "medial_pterygoid_left",
    "tongue",
    "digastric_right",
    "digastric_left",
    "larynx_air",
    "thyroid_cartilage",
    "hyoid",
    "cricoid_cartilage",
    "zygomatic_arch_right",
    "zygomatic_arch_left",
    "styloid_process_right",
    "styloid_process_left",
    "internal_carotid_artery_right",
    "internal_carotid_artery_left",
    "internal_jugular_vein_right",
    "internal_jugular_vein_left",
    "sternocleidomastoid_right",
    "sternocleidomastoid_left",
    "superior_pharyngeal_constrictor",
    "middle_pharyngeal_constrictor",
    "inferior_pharyngeal_constrictor",
    "trapezius_right",
    "trapezius_left",
    "platysma_right",
    "platysma_left",
    "levator_scapulae_right",
    "levator_scapulae_left",
    "anterior_scalene_right",
    "anterior_scalene_left",
    "middle_scalene_right",
    "middle_scalene_left",
    "posterior_scalene_right",
    "posterior_scalene_left",
    "sterno_thyroid_right",
    "sterno_thyroid_left",
    "thyrohyoid_right",
    "thyrohyoid_left",
    "prevertebral_right",
    "prevertebral_left",
    "liver_vessels",
    "liver_tumor",
    "eyeball_right",
    "lateral_rectus_muscle_right",
    "superior_oblique_muscle_right",
    "levator_palpebrae_superioris_right",
    "superior_rectus_muscle_right",
    "medial_rectus_muscle_left",
    "inferior_oblique_muscle_right",
    "inferior_rectus_muscle_right",
    "eyeball_left",
    "lateral_rectus_muscle_left",
    "superior_oblique_muscle_left",
    "levator_palpebrae_superioris_left",
    "superior_rectus_muscle_left",
    "medial_rectus_muscle_right",
    "inferior_oblique_muscle_left",
    "inferior_rectus_muscle_left",
    "lung",
    "lung_nodules",
    "breast",
    "liver_segment_1",
    "liver_segment_2",
    "liver_segment_3",
    "liver_segment_4",
    "liver_segment_5",
    "liver_segment_6",
    "liver_segment_7",
    "liver_segment_8",
    "mandible",
    "teeth_lower",
    "head",
    "sinus_maxillary",
    "sinus_frontal",
    "teeth_upper",
    "pectoralis_major_right",
    "pectoralis_major_left",
    "rectus_abdominis_right",
    "rectus_abdominis_left",
    "serratus_anterior_right",
    "serratus_anterior_left",
    "latissimus_dorsi_right",
    "latissimus_dorsi_left",
    "external_oblique_right",
    "external_oblique_left",
    "internal_oblique_right",
    "internal_oblique_left",
    "erector_spinae_right",
    "erector_spinae_left",
    "transversospinalis_right",
    "transversospinalis_left",
    "psoas_major_right",
    "psoas_major_left",
    "quadratus_lumborum_right",
    "quadratus_lumborum_left",
    "myocardium",
    "atrium_left",
    "ventricle_left",
    "atrium_right",
    "ventricle_right",
    "pulmonary_artery",
    "patella",
    "tibia",
    "fibula",
    "tarsal",
    "metatarsal",
    "phalanges_feet",
    "ulna",
    "radius",
    "carpal",
    "metacarpal",
    "phalanges_hand",
    "subcutaneous_fat",
    "torso_fat",
    "skeletal_muscle",
    "intermuscular_fat",
    "brainstem",
    "subarachnoid_space",
    "venous_sinuses",
    "septum_pellucidum",
    "cerebellum",
    "caudate_nucleus",
    "lentiform_nucleus",
    "insular_cortex",
    "internal_capsule",
    "ventricle",
    "central_sulcus",
    "frontal_lobe",
    "parietal_lobe",
    "occipital_lobe",
    "temporal_lobe",
    "thalamus",
    "quadriceps_femoris_left",
    "quadriceps_femoris_right",
    "thigh_medial_compartment_left",
    "thigh_medial_compartment_right",
    "thigh_posterior_compartment_left",
    "thigh_posterior_compartment_right",
    "sartorius_left",
    "sartorius_right",
    "deltoid",
    "supraspinatus",
    "infraspinatus",
    "subscapularis",
    "coracobrachial",
    "trapezius",
    "pectoralis_minor",
    "serratus_anterior",
    "teres_major",
    "triceps_brachii"
]

MR_STRUCTURES = [
    "spleen",
    "kidney_right",
    "kidney_left",
    "gallbladder",
    "liver",
    "stomach",
    "pancreas",
    "adrenal_gland_right",
    "adrenal_gland_left",
    "esophagus",
    "trachea",
    "thyroid_gland",
    "small_bowel",
    "duodenum",
    "colon",
    "urinary_bladder",
    "prostate",
    "sacrum",
    "vertebrae_L5",
    "vertebrae_L4",
    "vertebrae_L3",
    "vertebrae_L2",
    "vertebrae_L1",
    "vertebrae_T12",
    "vertebrae_T11",
    "vertebrae_T10",
    "vertebrae_T9",
    "vertebrae_T8",
    "vertebrae_T7",
    "vertebrae_T6",
    "vertebrae_T5",
    "vertebrae_T4",
    "vertebrae_T3",
    "vertebrae_T2",
    "vertebrae_T1",
    "vertebrae_C7",
    "vertebrae_C6",
    "vertebrae_C5",
    "vertebrae_C4",
    "vertebrae_C3",
    "vertebrae_C2",
    "vertebrae_C1",
    "heart",
    "aorta",
    "pulmonary_vein",
    "inferior_vena_cava",
    "portal_vein_and_splenic_vein",
    "iliac_artery_left",
    "iliac_artery_right",
    "iliac_vena_left",
    "iliac_vena_right",
    "humerus_left",
    "humerus_right",
    "scapula_left",
    "scapula_right",
    "clavicula_left",
    "clavicula_right",
    "femur_left",
    "femur_right",
    "hip_left",
    "hip_right",
    "spinal_cord",
    "gluteus_maximus_left",
    "gluteus_maximus_right",
    "gluteus_medius_left",
    "gluteus_medius_right",
    "gluteus_minimus_left",
    "gluteus_minimus_right",
    "autochthon_left",
    "autochthon_right",
    "iliopsoas_left",
    "iliopsoas_right",
    "brain",
    "intervertebral_discs",
    "patella",
    "tibia",
    "fibula",
    "tarsal",
    "metatarsal",
    "phalanges_feet",
    "ulna",
    "radius",
    "face",
    "subcutaneous_fat",
    "skeletal_muscle",
    "torso_fat",
    "quadriceps_femoris_left",
    "quadriceps_femoris_right",
    "thigh_medial_compartment_left",
    "thigh_medial_compartment_right",
    "thigh_posterior_compartment_left",
    "thigh_posterior_compartment_right",
    "sartorius_left",
    "sartorius_right",
    "deltoid",
    "supraspinatus",
    "infraspinatus",
    "subscapularis",
    "coracobrachial",
    "trapezius",
    "pectoralis_minor",
    "serratus_anterior",
    "teres_major",
    "triceps_brachii",
    "body_trunc",
    "body_extremities",
    "liver_segment_1",
    "liver_segment_2",
    "liver_segment_3",
    "liver_segment_4",
    "liver_segment_5",
    "liver_segment_6",
    "liver_segment_7",
    "liver_segment_8"
]

VALID_STRUCTURES = list(set(CT_STRUCTURES + MR_STRUCTURES))


def get_modality(ds) -> str:
    """Parse modality from a pydicom dataset. Returns 'CT', 'MR', or 'Other'."""
    mod = str(ds.get("Modality", "CT"))
    if "MR" in mod: return "MR"
    if "CT" in mod: return "CT"
    return "Other"


def get_valid_structures_for_modality(modality: str) -> list:
    """Return the structure list appropriate for the given modality string."""
    if modality == "MR":
        return MR_STRUCTURES
    return CT_STRUCTURES


def clean_url(url: str) -> str:
    """Strips frontend-specific prefixes like 'wadouri:' or 'dicomweb:'."""
    if not url: return ""
    return re.sub(r"^(wadouri:|dicomweb:)", "", url)


def extract_first_json(text: str):
    # 1. Try markdown code block first
    code_block = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
    if code_block:
        try:
            return json.loads(code_block.group(1))
        except Exception:
            pass

    # 2. Balance braces iteratively
    start = text.find("{")
    if start == -1:
        return None

    depth = 0
    in_string = False
    escape = False

    for i in range(start, len(text)):
        char = text[i]
        if in_string:
            if escape:
                escape = False
            elif char == '\\':
                escape = True
            elif char == '"':
                in_string = False
        else:
            if char == '"':
                in_string = True
            elif char == '{':
                depth += 1
            elif char == '}':
                depth -= 1
                if depth == 0:
                    candidate = text[start:i+1]
                    try:
                        return json.loads(candidate)
                    except Exception:
                        if candidate.startswith("{{") and candidate.endswith("}}"):
                            try:
                                return json.loads(candidate[1:-1])
                            except Exception:
                                pass
    return None